name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.3
      uses: actions/setup-node@v2
      with:
        node-version: '16.3'
    - name: Install yarn and run unittest
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Publish to Github Packages Registry
      uses: tuyencaovn/ghaction@master
      with:
        name: tuyencaovn/ghaction/gaction
        registry: ghcr.io
        username: ${{ secrets.TUYENCAO }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile-prod
        tags: latest